export const menu = [
  {
    id: 1,
    name: "Caesar Salad",
    category: "Starters",
    price: 8.5,
  },
  {
    id: 2,
    name: "Greek Salad",
    category: "Starters",
    price: 7.5,
  },
  {
    id: 3,
    name: "Tomato Soup",
    category: "Starters",
    price: 6,
  },
  {
    id: 4,
    name: "French Onion Soup",
    category: "Starters",
    price: 6.5,
  },
  {
    id: 5,
    name: "Garlic Bread",
    category: "Starters",
    price: 5,
  },
  {
    id: 6,
    name: "Spaghetti Bolognese",
    category: "Main Dishes",
    price: 12,
  },
  {
    id: 7,
    name: "Chicken Alfredo",
    category: "Main Dishes",
    price: 13,
  },
  {
    id: 8,
    name: "Beef Lasagna",
    category: "Main Dishes",
    price: 14,
  },
  {
    id: 9,
    name: "Grilled Salmon",
    category: "Main Dishes",
    price: 16,
  },
  {
    id: 10,
    name: "Chicken Parmesan",
    category: "Main Dishes",
    price: 13.5,
  },
  {
    id: 11,
    name: "Veggie Burger",
    category: "Main Dishes",
    price: 11,
  },
  {
    id: 12,
    name: "Margherita Pizza",
    category: "Main Dishes",
    price: 10,
  },
  {
    id: 13,
    name: "Pepperoni Pizza",
    category: "Main Dishes",
    price: 11.5,
  },
  {
    id: 14,
    name: "Chicken Wrap",
    category: "Sandwiches & Wraps",
    price: 9,
  },
  {
    id: 15,
    name: "Tuna Sandwich",
    category: "Sandwiches & Wraps",
    price: 8.5,
  },
  {
    id: 16,
    name: "Club Sandwich",
    category: "Sandwiches & Wraps",
    price: 9.5,
  },
  {
    id: 17,
    name: "Falafel Wrap",
    category: "Sandwiches & Wraps",
    price: 8,
  },
  {
    id: 18,
    name: "Chicken Fried Rice",
    category: "Asian Dishes",
    price: 12,
  },
  {
    id: 19,
    name: "Beef Noodles",
    category: "Asian Dishes",
    price: 13,
  },
  {
    id: 20,
    name: "Sushi Set",
    category: "Asian Dishes",
    price: 15,
  },
  {
    id: 21,
    name: "Pad Thai",
    category: "Asian Dishes",
    price: 12.5,
  },
  {
    id: 22,
    name: "Butter Chicken",
    category: "Indian",
    price: 13,
  },
  {
    id: 23,
    name: "Chicken Biryani",
    category: "Indian",
    price: 14,
  },
  {
    id: 24,
    name: "Paneer Tikka",
    category: "Indian",
    price: 12,
  },
  {
    id: 25,
    name: "Cheesecake",
    category: "Desserts",
    price: 6.5,
  },
  {
    id: 26,
    name: "Chocolate Brownie",
    category: "Desserts",
    price: 5.5,
  },
  {
    id: 27,
    name: "Ice Cream (Vanilla)",
    category: "Desserts",
    price: 4.5,
  },
  {
    id: 28,
    name: "Tiramisu",
    category: "Desserts",
    price: 6,
  },
  {
    id: 29,
    name: "Cola",
    category: "Drinks",
    price: 2.5,
  },
  {
    id: 30,
    name: "Lemonade",
    category: "Drinks",
    price: 2.5,
  },
  {
    id: 31,
    name: "Iced Tea",
    category: "Drinks",
    price: 2.5,
  },
  {
    id: 32,
    name: "Coffee",
    category: "Drinks",
    price: 3,
  },
  {
    id: 33,
    name: "Cappuccino",
    category: "Drinks",
    price: 3.5,
  },
];
